stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
      - src/data/data_ingestion.py
    params:
      - data_ingestion.test_size
      - data_ingestion.random_state
    outs:
      - Data/raw

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
      - Data/raw/train.csv
      - Data/raw/test.csv
      - src/data/data_preprocessing.py
    outs:
      - Data/interim
  